# Generated by Django 4.0.3 on 2022-05-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=500)),
                ('coin_price', models.CharField(max_length=500)),
                ('market_cap', models.CharField(max_length=500)),
                ('add_date', models.CharField(max_length=500)),
                ('total_supply', models.CharField(max_length=500)),
                ('circulating_supply', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('Title', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=500)),
                ('Date', models.CharField(max_length=500)),
                ('Link', models.CharField(max_length=500)),
            ],
        ),
    ]
